# Wow such recursion
name: cabueta-introspect
on:
  push:
  workflow_dispatch:

jobs:
  cabueta:
    uses: gbrls/cabueta/.github/workflows/cabueta.yml@main
    with:
      dast-check: false
      target-url: "http://URL_TO_THE_APPLICATION (e.g.: https://cabueta.com)"

